# login User

POST  http://localhost:7000/api/user/login
Content-Type: application/json

{"email":"wahab.cs238@gmail.com" ,"password":"12345"}



# create review
###

POST  http://localhost:7000/api/review/create/651afc4de46a7036827fac82
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjoiNjUxN2NiYjJmMzkwNmYyZjI1YTgzMjE4IiwiaWF0IjoxNjk2OTE1NTY2LCJleHAiOjE2OTcxNzQ3NjZ9.vHOZAhyXJNqKdLkv5TcyrRGtvSp2p52jAkh0Nl1AFY4

{
    "message":"another Review is done",
    "rating":4
}

###

# fetching all Products
GET   http://localhost:7000/api/product/
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjoiNjUxN2NiYjJmMzkwNmYyZjI1YTgzMjE4IiwiaWF0IjoxNjk2OTE1NTY2LCJleHAiOjE2OTcxNzQ3NjZ9.vHOZAhyXJNqKdLkv5TcyrRGtvSp2p52jAkh0Nl1AFY4



###
# fetching getting order
GET   http://localhost:7000/api/order/
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjoiNjUxN2NiYjJmMzkwNmYyZjI1YTgzMjE4IiwiaWF0IjoxNjk2OTE1NTY2LCJleHAiOjE2OTcxNzQ3NjZ9.vHOZAhyXJNqKdLkv5TcyrRGtvSp2p52jAkh0Nl1AFY4



