# ______________________________________________________________________
# ______________________________________________________________________
#                              USER ROUTES 
# ______________________________________________________________________
# ______________________________________________________________________

# register User
POST  http://localhost:7000/api/user/register
Content-Type: application/json

{
    "fullname": "wahab-adil",
    "email":"test12345@gmail.com",
    "password":"12345"
}
###

# register User

GET   http://localhost:7000/api/user/auth0/register
Content-Type: application/json

{
    "password":"adiljan"
}
###

# login User
POST  http://localhost:7000/api/user/login
Content-Type: application/json

{
    "email":"test12345@gmail.com",
    "password":"12345"
}

###

# change password
POST  http://localhost:7000/api/user/changepassword
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjoiNjUzMjE1MzFiYjQyYmYwNzQwYjllNWJkIiwiaWF0IjoxNzAxMjgyNzY5LCJleHAiOjE3MDE1NDE5Njl9.pLNki_b9LATudpH6IwrpHGHDOZAFOffuRehRV64SiSE

{
    "prevPassword":"12345",
    "newPassword":"54321"
}

###

# forgot password
POST  http://localhost:7000/api/user/forgot-password
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjoiNjUzMjE1MzFiYjQyYmYwNzQwYjllNWJkIiwiaWF0IjoxNzAxMjgyNzY5LCJleHAiOjE3MDE1NDE5Njl9.pLNki_b9LATudpH6IwrpHGHDOZAFOffuRehRV64SiSE


{
    "newPassword":"12345",
    "confirmPassword":"12345"
}

###

# send email

POST  http://localhost:7000/api/user/sendemail
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjoiNjUzMjE1MzFiYjQyYmYwNzQwYjllNWJkIiwiaWF0IjoxNzAwNzQzMDk3LCJleHAiOjE3MDEwMDIyOTd9.LF_gO7dlVBn_NgZaATDVLF_bgHnqm77wbkwhn8k9RW4

{
    "email":"wahab.cs238@gmail.com"
}

###

# resend email
POST  http://localhost:7000/api/user/sendemail
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjoiNjUzMjE1MzFiYjQyYmYwNzQwYjllNWJkIiwiaWF0IjoxNzAwNzQzMDk3LCJleHAiOjE3MDEwMDIyOTd9.LF_gO7dlVBn_NgZaATDVLF_bgHnqm77wbkwhn8k9RW4

{
    "email":"wahab.cs238@gmail.com"
}

###

# check otp
POST  http://localhost:7000/api/user/checkotp
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjoiNjUzMjE1MzFiYjQyYmYwNzQwYjllNWJkIiwiaWF0IjoxNzAwNzQzMDk3LCJleHAiOjE3MDEwMDIyOTd9.LF_gO7dlVBn_NgZaATDVLF_bgHnqm77wbkwhn8k9RW4

{
    "userotp":1198
}




###

# User profile

GET   http://localhost:7000/hell
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImtSWHJBUTV0OHlkRG1OU1VSYjJjMCJ9.eyJpc3MiOiJodHRwczovL2Rldi0yM3BscDhnNzdxamdvc3c0LnVzLmF1dGgwLmNvbS8iLCJzdWIiOiIyY3RieXlVcDBNNHc2T1ZvYnRmdGNleW9obldMMUY5WkBjbGllbnRzIiwiYXVkIjoiaHR0cDovL2xvY2FsaG9zdDo3MDAwIiwiaWF0IjoxNzAxNzA2MTIwLCJleHAiOjE3MDE3OTI1MjAsImF6cCI6IjJjdGJ5eVVwME00dzZPVm9idGZ0Y2V5b2huV0wxRjlaIiwiZ3R5IjoiY2xpZW50LWNyZWRlbnRpYWxzIn0.QH2g3TLN5CZJNAgnciw33Au_YwER90D89jjMSfYsOeYUqKrure9OjlCTXlxvRE8sVHJdZxf_oDiJ5yqtiIRwCZCyGzmBUkf5dJgbeptoB6RJcGL82X-Ei2Bz1uFy4DrQjodf7onWfm_J-TMj3RZKcj-6EXS7rBlFtAgB8UT8JFpgHrMCuZrTs1uoqVtL0BAokWaAjCjaB7OWY56MSd1pxMPl3d2WG49zui5l0rNkL_0g0q2cmKKWuQn4O1o9QlPuztH9eJfK72oiswi-8zNHWsAW-3inXfwOJPWE5WUNpUmchDHa-FDNjZl7MJAiOP7tEuAh8l3NRYycgKv7-94Xng

###


# Update User Shipping Address
POST    http://localhost:7000/api/user/update/shipping
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjoiNjUzMjE1MzFiYjQyYmYwNzQwYjllNWJkIiwiaWF0IjoxNjk4OTM3NTAzLCJleHAiOjE2OTkxOTY3MDN9.PTiiYR7k_6bVyxNYsNTzuHvJ4WEVN0fG4CguP8JNR7k

{
        "firstName":"Wahab",
        "lastName":"Adil",
        "address":"Helmand-Afghanistan",
        "city":"lashkar-gah",
        "postalCode":"3401",
        "province":"helmand",
        "country":"afghanistan",
        "phone":"0745180238"
}
# ///////////////////////////////////////////////////////////////////////





# ______________________________________________________________________
# ______________________________________________________________________
#                              PRODUCT ROUTES 
# ______________________________________________________________________
# ______________________________________________________________________


###
# create Product
POST  http://localhost:7000/api/product/create
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjoiNjUxN2NiYjJmMzkwNmYyZjI1YTgzMjE4IiwiaWF0IjoxNjk3NzM0MjM2LCJleHAiOjE2OTc5OTM0MzZ9.uCFWvGztihcrl8LiV9OHEDNkqGIeBgYjquyJ6MSSHCA
#  --- Sizes list for product is =["S", "M", "L", "XL", "XXL"],

{
    "name":"Product-name", 
    "description":"Description For Product",
     "brand":"brand-name", 
     "category":"category-name", 
     "sizes":"S",
     "colors":"Blue",
      "price":200,
       "totalQty":100
}
###

# update Product
PUT   http://localhost:7000/api/product/update/65321531bb42bf0740b9e5bd
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjoiNjUxN2NiYjJmMzkwNmYyZjI1YTgzMjE4IiwiaWF0IjoxNjk3NzM0MjM2LCJleHAiOjE2OTc5OTM0MzZ9.uCFWvGztihcrl8LiV9OHEDNkqGIeBgYjquyJ6MSSHCA
#  --- Sizes list for product is =["S", "M", "L", "XL", "XXL"],

{
    "name":"updated name of Product", 
    "description":"updated Description For Product",
     "brand":"updated Brand-name", 
     "category":"updated Category name", 
     "sizes":"XXL",
     "colors":"green",
      "price":100,
       "totalQty":50
}
###

###
#  Single Product
GET    http://localhost:7000/api/product/65321531bb42bf0740b9e5bd


###

#  all Product
GET    http://localhost:7000/api/product/all

###

#  filtering  Products

# assign your apptions for filtering product that you want
# like filtering by(name, color,brand, size,category , price(from-to) ),
# example : (name=helamd)
###

GET    http://localhost:7000/api/product/?name=helmand

###
#  delete  Product

DELETE   http://localhost:7000/api/product/delete/65321531bb42bf0740b9e5bd

###

# ///////////////////////////////////////////////////////////////////////



# ______________________________________________________________________
# ______________________________________________________________________
#                              BRAND ROUTES 
# ______________________________________________________________________
# ______________________________________________________________________


###
# create Brand
POST  http://localhost:7000/api/brand/create
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjoiNjUxN2NiYjJmMzkwNmYyZjI1YTgzMjE4IiwiaWF0IjoxNjk3NzM0MjM2LCJleHAiOjE2OTc5OTM0MzZ9.uCFWvGztihcrl8LiV9OHEDNkqGIeBgYjquyJ6MSSHCA

{
    "name":"brand-name"
}
###

# update Brand
PUT   http://localhost:7000/api/brand/update/653221bb5f5038faa596b8a2
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjoiNjUxN2NiYjJmMzkwNmYyZjI1YTgzMjE4IiwiaWF0IjoxNjk3NzM0MjM2LCJleHAiOjE2OTc5OTM0MzZ9.uCFWvGztihcrl8LiV9OHEDNkqGIeBgYjquyJ6MSSHCA

{
    "name":"updated name of Brand"
}
###

###
#  Single Brand
GET    http://localhost:7000/api/brand/653221bb5f5038faa596b8a2


###

#  all Brand
GET    http://localhost:7000/api/brand/

###
#  delete  Brand

DELETE   http://localhost:7000/api/brand/653221bb5f5038faa596b8a2

###

# /////////////////////////////////////////////////////////////////


# ______________________________________________________________________
# ______________________________________________________________________
#                              CATEGORY ROUTES 
# ______________________________________________________________________
# ______________________________________________________________________


###
# create category
POST  http://localhost:7000/api/category/create
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjoiNjUxN2NiYjJmMzkwNmYyZjI1YTgzMjE4IiwiaWF0IjoxNjk3NzM0MjM2LCJleHAiOjE2OTc5OTM0MzZ9.uCFWvGztihcrl8LiV9OHEDNkqGIeBgYjquyJ6MSSHCA

{
    "name":"category-name"
}
###

# update category
POST    http://localhost:7000/api/category/update/6532236d5f5038faa596b8ac
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjoiNjUxN2NiYjJmMzkwNmYyZjI1YTgzMjE4IiwiaWF0IjoxNjk3NzM0MjM2LCJleHAiOjE2OTc5OTM0MzZ9.uCFWvGztihcrl8LiV9OHEDNkqGIeBgYjquyJ6MSSHCA

{
    "name":"updated name of Category"
}
###

###
#  Single Category
GET    http://localhost:7000/api/category/6532236d5f5038faa596b8ac
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjoiNjUxN2NiYjJmMzkwNmYyZjI1YTgzMjE4IiwiaWF0IjoxNjk3NzM0MjM2LCJleHAiOjE2OTc5OTM0MzZ9.uCFWvGztihcrl8LiV9OHEDNkqGIeBgYjquyJ6MSSHCA


###

#  all category
GET    http://localhost:7000/api/category/
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjoiNjUxN2NiYjJmMzkwNmYyZjI1YTgzMjE4IiwiaWF0IjoxNjk3NzM0MjM2LCJleHAiOjE2OTc5OTM0MzZ9.uCFWvGztihcrl8LiV9OHEDNkqGIeBgYjquyJ6MSSHCA


###
#  delete  category

DELETE   http://localhost:7000/api/category/6532236d5f5038faa596b8ac

###

# /////////////////////////////////////////////////////////////////




# ______________________________________________________________________
# ______________________________________________________________________
#                              COLOR ROUTES 
# ______________________________________________________________________
# ______________________________________________________________________


###
# create color
POST  http://localhost:7000/api/color/create
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjoiNjUxN2NiYjJmMzkwNmYyZjI1YTgzMjE4IiwiaWF0IjoxNjk3NzM0MjM2LCJleHAiOjE2OTc5OTM0MzZ9.uCFWvGztihcrl8LiV9OHEDNkqGIeBgYjquyJ6MSSHCA

{
    "name":"color-name"
}
###

# update color
PUT     http://localhost:7000/api/color/update/653224c05f5038faa596b8b5
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjoiNjUxN2NiYjJmMzkwNmYyZjI1YTgzMjE4IiwiaWF0IjoxNjk3NzM0MjM2LCJleHAiOjE2OTc5OTM0MzZ9.uCFWvGztihcrl8LiV9OHEDNkqGIeBgYjquyJ6MSSHCA

{
    "name":"updated name of color"
}
###

###
#  Single color
GET    http://localhost:7000/api/color/653224c05f5038faa596b8b5


###

#  all color
GET    http://localhost:7000/api/color/


###
#  delete  color

DELETE   http://localhost:7000/api/color/653224c05f5038faa596b8b5

###

# /////////////////////////////////////////////////////////////////

# /////////////////////////////////////////////////////////////////




# ______________________________________________________________________
# ______________________________________________________________________
#                              Review ROUTES 
# ______________________________________________________________________
# ______________________________________________________________________


###
# create review

POST  http://localhost:7000/api/review/create/653227015595002725aad49d
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjoiNjUxN2NiYjJmMzkwNmYyZjI1YTgzMjE4IiwiaWF0IjoxNjk3NzM0MjM2LCJleHAiOjE2OTc5OTM0MzZ9.uCFWvGztihcrl8LiV9OHEDNkqGIeBgYjquyJ6MSSHCA

{
    "message":"great",
    "rating":4
}

# /////////////////////////////////////////////////////////////////

# /////////////////////////////////////////////////////////////////





# ______________________________________________________________________
# ______________________________________________________________________
#                              ORDER ROUTES 
# ______________________________________________________________________
# ______________________________________________________________________


###
# create order
POST    http://localhost:7000/api/order/create
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjoiNjUzMjE1MzFiYjQyYmYwNzQwYjllNWJkIiwiaWF0IjoxNjk5MjAzNjE2LCJleHAiOjE2OTk0NjI4MTZ9.gZq2j7UM2uny9eep--QSoOech-bezRQIfqVlGMLVJng

{
    "orderItems":[
        {
            "_id":"653227015595002725aad49d",
            "name":"football-shirt",
            "totalQty":2,
            "totalQtyBuying":2
        }
           ]
        ,
    "totalPrice":1500,
    "shippingAddress":{
        "firstname":"Adiljan",
        "postalAddress":"Helmand Afghanistan"
    } 

}


###
# fetch all orders
GET   http://localhost:7000/api/order/
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjoiNjUzMjE1MzFiYjQyYmYwNzQwYjllNWJkIiwiaWF0IjoxNjk4ODI1MTAwLCJleHAiOjE2OTkwODQzMDB9.8wFnFylSzd-KFHDiHMtd6nwxsRn3FRr-ugqSP_5UHzM

###
# fetch Single Order
GET   http://localhost:7000/api/order/6547da5d0c367795d89e8086
Content-Type: application/json

###
# fetch statistic of sales 
GET   http://localhost:7000/api/order/sales/stats

###
# update  Order
PUT  http://localhost:7000/api/order/update/65426fb4b65fbac6d01e924e
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjoiNjUzMjE1MzFiYjQyYmYwNzQwYjllNWJkIiwiaWF0IjoxNjk4ODI1MTAwLCJleHAiOjE2OTkwODQzMDB9.8wFnFylSzd-KFHDiHMtd6nwxsRn3FRr-ugqSP_5UHzM

{"status": "processing"}



# /////////////////////////////////////////////////////////////////

# /////////////////////////////////////////////////////////////////





# ______________________________________________________________________
# ______________________________________________________________________
#                              COUPEN ROUTES 
# ______________________________________________________________________
# ______________________________________________________________________


###
# create coupen
POST    http://localhost:7000/api/coupen/create
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjoiNjUzMjE1MzFiYjQyYmYwNzQwYjllNWJkIiwiaWF0IjoxNjk5NjI3MTAzLCJleHAiOjE2OTk4ODYzMDN9.WDLMEEl68Un6XUhaID3SBFp8NcTgcv23i7rzSFruD-c

{
"code":"new sale2",
"startDate":"11-20-2023",
"endDate":"12-20-2023",
"discount":50

}

###
# update coupen
PUT     http://localhost:7000/api/coupen/update/6550efb2963e076babc22a9c
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjoiNjUzMjE1MzFiYjQyYmYwNzQwYjllNWJkIiwiaWF0IjoxNjk5ODkxNzU1LCJleHAiOjE3MDAxNTA5NTV9.R7W_r2EMnvd1oQgcIxqn44SVVK_Zs-sbyZwmmvmoTIM

{
"code":"adiljan",
"startDate":"11-20-2023",
"endDate":"12-20-2023",
"discount":22

}

###
# get all coupons
GET     http://localhost:7000/api/coupen/
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjoiNjUzMjE1MzFiYjQyYmYwNzQwYjllNWJkIiwiaWF0IjoxNjk5NjI3MTAzLCJleHAiOjE2OTk4ODYzMDN9.WDLMEEl68Un6XUhaID3SBFp8NcTgcv23i7rzSFruD-c

###
# get single coupon
GET     http://localhost:7000/api/coupen/6550efb2963e076babc22a9c
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjoiNjUzMjE1MzFiYjQyYmYwNzQwYjllNWJkIiwiaWF0IjoxNjk5ODkxNzU1LCJleHAiOjE3MDAxNTA5NTV9.R7W_r2EMnvd1oQgcIxqn44SVVK_Zs-sbyZwmmvmoTIM


###
# delete single coupon
DELETE      http://localhost:7000/api/coupen/6550efb2963e076babc22a9c
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjoiNjUzMjE1MzFiYjQyYmYwNzQwYjllNWJkIiwiaWF0IjoxNjk5ODkxNzU1LCJleHAiOjE3MDAxNTA5NTV9.R7W_r2EMnvd1oQgcIxqn44SVVK_Zs-sbyZwmmvmoTIM

